"""T-010: Startup verification — app object, route registration, CORS config."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.routing import APIRoute

from app.main import app


# ── Helper: collect all API paths from app.routes ─────────
def _get_all_route_paths() -> set[str]:
    """Extract all API paths from the app, including included routers."""
    paths: set[str] = set()
    for route in app.routes:
        # Direct APIRoute (/, /health, /docs, /openapi.json)
        if hasattr(route, "path"):
            paths.add(route.path)
        # IncludedRouter wraps a sub-router via include_router
        elif hasattr(route, "original_router"):
            for sub in route.original_router.routes:
                if hasattr(sub, "path"):
                    paths.add(sub.path)
    return paths


# ── Test 1: app object exists and is a FastAPI instance ────
def test_app_is_fastapi():
    assert isinstance(app, FastAPI)
    assert app.title == "可可语伴AI客服系统"


# ── Test 2: all expected routes are registered ────────────
def test_all_routes_registered():
    """Verify that all 9 expected API paths are present in app.routes."""
    api_paths = _get_all_route_paths()

    expected = {
        "/",
        "/api/auth/login",
        "/api/auth/me",
        "/api/chat",
        "/api/logs",
        "/api/logs/{trace_id}",
        "/api/sessions",
        "/api/sessions/{session_id}/messages",
        "/health",
    }

    missing = expected - api_paths
    extra = api_paths - expected

    assert not missing, f"Required routes missing: {sorted(missing)}"
    # Extra is fine (docs, redoc, openapi.json are autogenerated)


# ── Test 3: CORS middleware is configured ─────────────────
def test_cors_middleware_configured():
    """Verify CORS middleware is present with restricted origins."""
    user_middleware = getattr(app, "user_middleware", [])
    cors_found = False

    for um in user_middleware:
        if um.cls == CORSMiddleware:
            origins = um.kwargs.get("allow_origins", [])
            assert "http://localhost:5173" in origins, (
                f"Expected localhost:5173 in CORS origins, got: {origins}"
            )
            cors_found = True
            break

    assert cors_found, "CORSMiddleware not found in app.user_middleware"


# ── Test 4: health endpoint exists ────────────────────────
def test_health_route():
    """The /health route should be registered."""
    assert "/health" in _get_all_route_paths()


# ── Test 5: exception handlers are registered ────────────
def test_exception_handlers_registered():
    """HTTPException and generic Exception handlers should be registered."""
    from fastapi import HTTPException

    assert HTTPException in app.exception_handlers
    assert Exception in app.exception_handlers
