"""话题讨论主题配置（T-005）。

每个主题包含：id、名称、图标、分类、描述、难度、引入引导、
展开问题、总结引导。
"""

DISCUSSION_TOPICS = {
    "climate": {
        "id": "climate",
        "name": "气候变化",
        "icon": "🌍",
        "category": "society",
        "description": "讨论气候变化的原因、影响和应对措施",
        "difficulty": "hard",
        "introduction": "气候变化是当今世界面临的最大挑战之一。",
        "expansion_questions": [
            "你认为气候变化的主要原因是什么？",
            "气候变化对你的生活有影响吗？",
            "政府应该采取什么措施应对气候变化？",
            "个人能为减缓气候变化做什么？",
            "你认为发达国家和发展中国家谁应该承担更多责任？",
        ],
        "summary_prompt": "总结本次讨论，提出你的核心观点。",
    },
    "education": {
        "id": "education",
        "name": "教育",
        "icon": "📚",
        "category": "society",
        "description": "讨论教育的目的、方法和未来",
        "difficulty": "medium",
        "introduction": "教育是改变个人和社会的重要途径。",
        "expansion_questions": [
            "你认为教育的目的是什么？",
            "传统教育和在线教育哪个更好？",
            "应该更注重知识还是能力培养？",
            "未来教育会变成什么样？",
            "你觉得中国教育体系有哪些优势和不足？",
        ],
        "summary_prompt": "总结你对教育的看法。",
    },
    "ai_future": {
        "id": "ai_future",
        "name": "人工智能",
        "icon": "🤖",
        "category": "technology",
        "description": "讨论 AI 对社会和个人的影响",
        "difficulty": "hard",
        "introduction": "人工智能正在深刻改变我们的工作和生活方式。",
        "expansion_questions": [
            "你认为 AI 会取代人类工作吗？",
            "AI 在教育中应该扮演什么角色？",
            "你担心 AI 的安全问题吗？",
            "AI 应该如何被监管？",
            "你愿意让 AI 帮你做重要决定吗？",
        ],
        "summary_prompt": "总结你对 AI 时代的看法。",
    },
    "social_media": {
        "id": "social_media",
        "name": "社交媒体",
        "icon": "📱",
        "category": "society",
        "description": "讨论社交媒体对生活的影响",
        "difficulty": "medium",
        "introduction": "社交媒体已成为现代人生活的一部分。",
        "expansion_questions": [
            "社交媒体对青少年的影响是正面还是负面？",
            "你每天花多少时间在社交媒体上？",
            "应该限制社交媒体使用吗？",
            "社交媒体让你更孤独还是更连接？",
            "没有社交媒体的一天会是什么样？",
        ],
        "summary_prompt": "总结你对社交媒体的看法。",
    },
    "remote_work": {
        "id": "remote_work",
        "name": "远程办公",
        "icon": "🏠",
        "category": "society",
        "description": "讨论远程办公的利弊与未来",
        "difficulty": "medium",
        "introduction": "远程办公正在改变传统的工作模式。",
        "expansion_questions": [
            "远程办公的优缺点是什么？",
            "哪些职业适合远程办公？",
            "远程办公会影响团队合作吗？",
            "你更喜欢远程还是办公室办公？",
            "未来工作模式会变成什么样？",
        ],
        "summary_prompt": "总结你对远程办公的看法。",
    },
    "urban_life": {
        "id": "urban_life",
        "name": "城市生活",
        "icon": "🏙️",
        "category": "society",
        "description": "讨论城市生活的吸引力与挑战",
        "difficulty": "medium",
        "introduction": "越来越多的人选择在城市生活。",
        "expansion_questions": [
            "你喜欢在城市还是乡村生活？",
            "城市生活最大的吸引力是什么？",
            "城市面临哪些问题？",
            "大城市和小城市你选哪个？",
            "理想中的宜居城市是什么样？",
        ],
        "summary_prompt": "总结你对城市生活的看法。",
    },
}
