"""自由对话话题配置（T-005）。

每个话题包含：id、名称、图标、分类、描述、难度、引导问题列表。
"""

FREECHAT_TOPICS = {
    "weekend": {
        "id": "weekend",
        "name": "周末活动",
        "icon": "🎉",
        "category": "personal",
        "description": "聊聊你的周末生活",
        "difficulty": "easy",
        "guiding_questions": [
            "你周末通常做什么？",
            "你更喜欢待在家里还是出门？",
            "你最近做过最有趣的事是什么？",
            "你周末会和朋友一起做什么？",
            "你想在周末尝试什么新活动？",
        ],
    },
    "travel": {
        "id": "travel",
        "name": "旅行经历",
        "icon": "✈️",
        "category": "travel",
        "description": "分享你的旅行故事和梦想目的地",
        "difficulty": "medium",
        "guiding_questions": [
            "你去过的最难忘的地方是哪里？",
            "你更喜欢国内游还是国外游？",
            "旅行对你意味着什么？",
            "你下次想去哪里旅行？",
            "你旅行时更喜欢规划还是随心走？",
        ],
    },
    "technology": {
        "id": "technology",
        "name": "科技与生活",
        "icon": "💻",
        "category": "technology",
        "description": "探讨科技如何改变我们的生活方式",
        "difficulty": "hard",
        "guiding_questions": [
            "你每天花多少时间在手机上？",
            "科技让生活更好了还是更糟了？",
            "你觉得 AI 未来会取代人类工作吗？",
            "你更喜欢线上社交还是线下社交？",
            "未来 10 年你最期待什么科技？",
        ],
    },
    "food": {
        "id": "food",
        "name": "美食文化",
        "icon": "🍜",
        "category": "culture",
        "description": "聊聊你喜欢的美食和饮食文化",
        "difficulty": "medium",
        "guiding_questions": [
            "你最喜欢什么食物？为什么？",
            "你吃过最特别的食物是什么？",
            "你更喜欢在家做饭还是外出就餐？",
            "你对中国菜和西餐有什么看法？",
            "如果你只能吃一种食物一辈子，你会选什么？",
        ],
    },
    "movies": {
        "id": "movies",
        "name": "电影与故事",
        "icon": "🎬",
        "category": "culture",
        "description": "分享你喜欢的电影和观影体验",
        "difficulty": "easy",
        "guiding_questions": [
            "你最近看过什么好电影？",
            "你更喜欢什么类型的电影？",
            "你觉得电影比书好吗？",
            "你更喜欢去电影院还是在家看？",
            "如果让你推荐一部电影给外国人，你会推荐什么？",
        ],
    },
    "sports": {
        "id": "sports",
        "name": "运动与健康",
        "icon": "🏃",
        "category": "personal",
        "description": "聊聊运动习惯和健康生活",
        "difficulty": "easy",
        "guiding_questions": [
            "你平时喜欢什么运动？",
            "你多久锻炼一次？",
            "运动对你的生活有什么影响？",
            "你觉得保持健康最重要的是什么？",
            "你想尝试什么新的运动项目？",
        ],
    },
    "music": {
        "id": "music",
        "name": "音乐",
        "icon": "🎵",
        "category": "culture",
        "description": "分享你喜欢的音乐类型和歌手",
        "difficulty": "easy",
        "guiding_questions": [
            "你喜欢什么类型的音乐？",
            "你最喜欢的歌手或乐队是谁？",
            "音乐在你的生活中扮演什么角色？",
            "你喜欢现场音乐还是录音室版本？",
            "如果你能学会一种乐器，你会选什么？",
        ],
    },
    "career": {
        "id": "career",
        "name": "职业规划",
        "icon": "💼",
        "category": "society",
        "description": "聊聊你的工作与职业梦想",
        "difficulty": "medium",
        "guiding_questions": [
            "你现在做什么工作？",
            "你理想中的工作是什么？",
            "工作与生活的平衡重要吗？",
            "你觉得未来职业会怎么变化？",
            "你如何应对工作压力？",
        ],
    },
    "environment": {
        "id": "environment",
        "name": "环保生活",
        "icon": "🌱",
        "category": "society",
        "description": "聊聊环保习惯和可持续生活",
        "difficulty": "medium",
        "guiding_questions": [
            "你平时有环保习惯吗？",
            "你觉得个人能影响环境吗？",
            "你使用过可重复利用的物品吗？",
            "环保和便利如何平衡？",
            "你身边有人做环保吗？",
        ],
    },
    "learning": {
        "id": "learning",
        "name": "学习习惯",
        "icon": "📖",
        "category": "personal",
        "description": "聊聊你的学习方法和习惯",
        "difficulty": "easy",
        "guiding_questions": [
            "你平时怎么学习新东西？",
            "你更擅长自学还是有老师教？",
            "学习中最难克服的障碍是什么？",
            "你如何保持学习动力？",
            "你最近在学什么？",
        ],
    },
    "daily": {
        "id": "daily",
        "name": "你的一天",
        "icon": "☀️",
        "category": "personal",
        "description": "描述你的一天如何度过",
        "difficulty": "easy",
        "guiding_questions": [
            "你通常几点起床？",
            "你一天中最喜欢的时刻是什么？",
            "你的工作日和周末有什么不同？",
            "你会怎么安排晚上的时间？",
            "如果有一天完全自由，你会做什么？",
        ],
    },
    "future": {
        "id": "future",
        "name": "未来畅想",
        "icon": "🔮",
        "category": "technology",
        "description": "畅想未来 10 年的生活变化",
        "difficulty": "hard",
        "guiding_questions": [
            "你觉得 10 年后生活会变成什么样？",
            "你最期待未来的什么技术？",
            "你担心未来吗？担心什么？",
            "你希望未来的自己是什么样？",
            "未来的人类还需要学习外语吗？",
        ],
    },
}
